package org.apache.vaadin.ui.partial;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * Created by tringuyen on 10/18/16.
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class FooterDesign extends VerticalLayout {
    public FooterDesign() {
        Design.read(this);
    }
}